### ISSUE TITLE
不支持vue2.0

### ISSUE THREAD

**Issue by LinWeiLong** [deboyblog/vue-wechat-title#1]
vue2.0的Vue.directive API变了，bind的方法第一个参数是元素本身，第二个参数的value属性才是传递进去指令的值

**Comment by deboyblog** [comment]
@LinWeiLong 已适配并测试通过 请看readme安装对应版本 [vuejs2.0 Demo](https://github.com/deboyblog/vue-wechat-title-demo/tree/2.0)
