### ISSUE TITLE
新版微信中已经不能用了

### ISSUE THREAD

**Issue by czl1378** [deboyblog/vue-wechat-title#11]

**Comment by deboyblog** [comment]
iOS 6.5.8 经测试 依旧正常 
地址：[http://vue-wechat-title.deboy.cn](http://vue-wechat-title.deboy.cn)
如果不能访问 请告知手机机型以及微信版本 谢谢

**Comment by czl1378** [comment]
不好意思，是IOS微信6.5.5版

在 2017-05-19 00:58:08，"Deboy" <notifications@github.com> 写道：


iOS 6.5.8 经测试 依旧正常
地址：http://vue-wechat-title.deboy.cn
如果不能访问 请告知手机机型以及微信版本 谢谢

**Comment by deboyblog** [comment]
由于iOS无法降级安装软件
请问是否方便升级微信版本再尝试 ?
还有请问使用的 Vuejs 版本是否是 2.x ?

**Comment by no-simple** [comment]
vue-wechat-title.js?682e:21 GET http://localhost:8080/favicon.ico 404 (Not Found)
会有这个错误

**Comment by deboyblog** [comment]
@no-simple 请把站标 (favicon.ico) 放置打包后的根目录下

**Comment by no-simple** [comment]
没有站标也会报错。我把  iframe.setAttribute('src', img || '/favicon.ico') 改成了
iframe.setAttribute('src', img ) 没有报错了，但不知道影响如何

**Comment by deboyblog** [comment]
@no-simple 插件原理是加载一个iframe(src是一张图片) img-set 就是设置这个图片地址的 如果没有站标 只是报404错误 你可以改成任意静态图片的地址 为了避免插件不生效 请按照说明设置
