### ISSUE TITLE
为什么我添加了vue-wechat-title不起作用阿

### ISSUE THREAD

**Issue by zhangwei900808** [deboyblog/vue-wechat-title#12]
![image](https://user-images.githubusercontent.com/4385154/27266600-0e2d7050-54d5-11e7-9244-b305f25840ed.png)

**Comment by deboyblog** [comment]
贴上main.js 还有在App.vue中使用的代码

**Comment by zhangwei900808** [comment]
@deboyblog 我的错，忘了加这行代码：
```
<router-view v-wechat-title="$route.meta.title"></router-view>
```
