### ISSUE TITLE
如何解决webpack下用了favicon后，vue-wechat-title报的警告

### ISSUE THREAD

**Issue by wLove-c** [deboyblog/vue-wechat-title#13]
vue-wechat-title.js?7221:21 Resource interpreted as Document but transferred with MIME type image/x-icon: "http://localhost:8080/favicon.ico".

**Comment by deboyblog** [comment]
1.在 `dev` 期间忽略 在 `build` 之后添加站标(`favicon.ico`)
2.把 `img-set` 指向 `static` 下的一个比较小的图片 或者 把 `favicon.ico` 复制一份放 `static` 目录下
