### ISSUE TITLE
在子路由下 title不显示

### ISSUE THREAD

**Issue by zhangchenna** [deboyblog/vue-wechat-title#14]
在子路由下 title不显示 ， {
                path: '/HomePage',
                component: HomePage,
                meta: {
                    title: '喜马拉雅FM',
                    allowBack: false
                },
                children: [
                    {
                        path: 'detail_one',
                        component: detail_one,
                        mate: {
                            keepAlive: true
                        }
                    },
                    {
                        path: 'detail_two',
                        component: detail_two,
                        mate: {
                            keepAlive: true
                        }
                    }
                ]
            },

**Comment by deboyblog** [comment]
显示为空?

**Comment by whdeairen** [comment]
@deboyblog 

path: '/',
      redirect: '/foot1',
      name: 'foot',
      
      component: foot,
      meta: { keepAlive: true,title: '首页'},
      children: [
        { path: '/foot1',name:'foot1',component: resolve => require(['../components/common/foot1.vue'], resolve),meta: { keepAlive: true,title: '第一页' } },
        { path: '/foot2',name:'foot2', component: resolve => require(['../components/common/foot2.vue'], resolve),meta: { keepAlive: true,title: '第二页'} },
        { path: '/foot3',name:'foot3', component: resolve => require(['../components/common/foot3.vue'], resolve),meta: { keepAlive: true,title: '第三页'} },
        { path: '/foot4',name:'foot4', component: resolve => require(['../components/common/foot4.vue'], resolve),meta: { keepAlive: true,title: '第四页'} },
      ]


这样的话 子组件的显示的还父组件的title

**Comment by deboyblog** [comment]
`App.vue` 定义一个计算变量来试试
 ``` 
computed: {
  title: {
    cache: false,
    get () {
      return this.$route.meta.title
    }
  }
}
```

**Comment by whdeairen** [comment]
@deboyblog 

foot（父组件）

html  <div v-we chat-title="title"></div>

计算属性

	computed: {
		title: {
			cache: false,
			get() {
				console.log(this.$route.meta.title);
				return this.$route.meta.title
			}
		}
	},

这里点击每次都打印的父组件的title

**Comment by deboyblog** [comment]
@whdeairen 你试试打印 `this.$route` 看能否找到子组件的信息

**Comment by deboyblog** [comment]
长时间未反馈 关闭
