### ISSUE TITLE
router切换标题抖动

### ISSUE THREAD

**Issue by Kuohao-wu** [deboyblog/vue-wechat-title#16]
使用此插件的时候，在微信浏览器下，按手机的返回键返回上一级路由，标题会发生抖动。作者给出的deom，在我手机测试也会发生抖动

**Comment by deboyblog** [comment]
方便报下机型吗?
手机型号
系统内核版本
微信版本
`vue-wechat-title` 版本

**Comment by Kuohao-wu** [comment]
手机型号：红米4高配
系统内核：Android6.0
微信版本：6.5.16
vue-wechat-title: 2.0

**Comment by deboyblog** [comment]
目前最新版的是 `2.0.4` 请打开 `node_modules/vue-wechat-title` 中的 `package.json` 查看具体版本

**Comment by whdeairen** [comment]
2.04一样的抖动

**Comment by Kuohao-wu** [comment]
刚刚查看了一下，package.json.确实是2.0.4版本。

**Comment by whdeairen** [comment]
@deboyblog  乐视2，安卓6.0 。前进没啥问题，返回抖动几次，感觉好像设置了两三次的样子，

**Comment by deboyblog** [comment]
不使用该插件是否同样有此问题?

**Comment by YDZ-94** [comment]
你好！我按文档操作后，直接那手机微信扫本地二维码，是可以修改title的，但是打包发布到测试环境后就无效了！IOS 安卓都一样！

**Comment by deboyblog** [comment]
@YDZ-94 请贴下引入和使用的代码

**Comment by xlei1123** [comment]
vue 单页面应用，在组件使用了v-wechat-title的时候 所有的资源文件都重新加载了一次（没有设置缓存的情况下），不知道是不是iframe引起的，望重视！！！

**Comment by deboyblog** [comment]
@xlei1123 设置下 `img-set` 属性 并且保证该路径的图片能访问 建议在 static 目录下放一个静态的小图片
