### ISSUE TITLE
网页标题的小图片也不显示

### ISSUE THREAD

**Issue by whdeairen** [deboyblog/vue-wechat-title#17]
<router-view v-if="$route.meta.keepAlive" v-wechat-title="$route.meta.title" img-set="/static/favicon.png"></router-view>

**Comment by whdeairen** [comment]
<router-view v-if="$route.meta.keepAlive" v-wechat-title="$route.meta.title" img-set="/static/favicon.png"></router-view>

**Comment by deboyblog** [comment]
开发阶段还是生产阶段?  `chrome`浏览器`console`栏报错是什么
提问题麻烦带上这些信息 否则不予解决
