### ISSUE TITLE
哈喽，想问下不引用ico的问题

### ISSUE THREAD

**Issue by ekkoJ** [deboyblog/vue-wechat-title#18]
额我现在不需要引用ico的情况下应该怎么设置？没有设置的话每次更换title都会报错……

**Comment by deboyblog** [comment]
把logo或者任意图片放至static目录下 填写 static 的相对路劲即可
比如 /static/logo.png

**Comment by ekkoJ** [comment]
<img width="446" alt="2017-11-20 2 31 21" src="https://user-images.githubusercontent.com/14833599/33005155-39dcca10-cd8a-11e7-852a-593dce570d2f.png">
<img width="348" alt="2017-11-20 2 31 44" src="https://user-images.githubusercontent.com/14833599/33005156-3a21a734-cd8a-11e7-9d75-cc93893ab40a.png">
依然有问题……

**Comment by deboyblog** [comment]
调试工具? 你手机连上wifi用局域网地址访问就不会了

**Comment by ekkoJ** [comment]
实测没问题~三扣~~回复速度好快啊~

**Comment by deboyblog** [comment]
在上班 盯着电脑呢
