### ISSUE TITLE
微信开发者报错

### ISSUE THREAD

**Issue by web0428** [deboyblog/vue-wechat-title#19]
VM12556:1 Refused to connect to 'ws://127.0.0.1:9974/' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by deboyblog** [comment]
并未是本插件的问题 
所报错提示的字段 本插件均未涉及到
包括 `websocket` 连接  更不可能会有了...

**Comment by web0428** [comment]
可是使用了插件才出来的这个问题，之前也是出现了这个问题

**Comment by deboyblog** [comment]
贴下代码

**Comment by web0428** [comment]
app.vue:
<template>
  <div id="app" v-wechat-title="$route.meta.title" >
  	<transition name="router-fade" mode="out-in">
	    <router-view ></router-view>
	</transition>
  </div>
</template>

router index:
{
      path: '/',
      meta:{
        title : "标题" 
      },
      component: function (resolve){
        require(['@/components/index'],resolve)
      }
    },

main:
import VueWechatTitle from 'vue-wechat-title';  
Vue.use(VueWechatTitle);

之前的项目也用过本插件的，好像并未发现该原因

**Comment by web0428** [comment]
<template>
  <div id="app" v-wechat-title="$route.meta.title" >
  	<transition name="router-fade" mode="out-in">
	    <router-view ></router-view>
	</transition>
  </div>
</template>

**Comment by web0428** [comment]
app:<div id="app" v-wechat-title="$route.meta.title" >
  	<transition name="router-fade" mode="out-in">
	    <router-view ></router-view>
	</transition>
  </div>

**Comment by deboyblog** [comment]
代码没有贴好

**Comment by web0428** [comment]
[<div id="app" v-wechat-title="$route.meta.title" >
  	<transition name="router-fade" mode="out-in">
	    <router-view ></router-view>
	</transition>
  </div>]

**Comment by web0428** [comment]
html发不出来我的天，app.vue里面的

**Comment by web0428** [comment]
`<div id="app" v-wechat-title="$route.meta.title" >
  	<transition name="router-fade" mode="out-in">
	    <router-view ></router-view>
	</transition>
  </div>`

**Comment by deboyblog** [comment]
代码 都要加 两个符号 `` 括起来

**Comment by web0428** [comment]
div id="app" v-wechat-title="$route.meta.title" 
transition name="router-fade" mode="out-in"
router-view router-view
transition
div
这样看吧

**Comment by web0428** [comment]
不知道为了什么，只要进入我配置了title的页面就会报错，但是标题正常显示了

**Comment by deboyblog** [comment]
加QQ 55631825 远程看

**Comment by web0428** [comment]
加不了你加我喃，1773626344

**Comment by deboyblog** [comment]
设置了`img-set`属性即可 
加载`iframe`(失败)导致`websocket`的跨域报错
