### ISSUE TITLE
微信iOS浏览器内核近期会切换为WKWebview，测试了一下无效

### ISSUE THREAD

**Issue by airyland** [deboyblog/vue-wechat-title#2]
原来的UIWebView可用，但是手动切换到WKWebview时无效。

**Comment by wolfsilver** [comment]
同求解决方案

**Comment by limichange** [comment]
据说3月会支持修改title，目前只能等了。

**Comment by flower0824** [comment]
已经困惑很久了，3月份会支持修改吗

**Comment by wolfsilver** [comment]
```
window.WeixinJSBridge.invoke('setPageTitle', {
        'title':"Title"
    }, function(res){

}) 
```
听说这个可以用

**Comment by mishe** [comment]
@wolfsilver 经过 测试无效

**Comment by deboyblog** [comment]
各位先不要着急 既然微信说了会出方案 就耐心一点等 我会关注这方面的更新 及时提出解决方案

**Comment by chenpengjun** [comment]
这种方案每次路由切换会造成页面刷新的
IOS WKWebview 网页开发适配指南，在单页应用中通过document.title多次修改原生title的方法将失效，该问题将于微信3月份发布的版本中解决
解决方案是什么？？？

**Comment by freefish1218** [comment]
微信不是说3/1前更新内核吗？好象并木有啊！……

**Comment by limichange** [comment]
微信上一次的更新是2.13。修复只能等他更新了。

**Comment by deboyblog** [comment]
做个标记：[iOS WKWebview 网页开发适配指南](https://mp.weixin.qq.com/advanced/wiki?t=t=resource/res_main&id=mp1483682025_enmey)

**Comment by deboyblog** [comment]
官方回复
![qq20170309-212655](https://cloud.githubusercontent.com/assets/11410323/23752204/4d49f8c8-050f-11e7-9824-3cb1f60deae0.png)
最新jssdk版本1.2.0: https://res.wx.qq.com/open/js/jweixin-1.2.0.js

**Comment by limichange** [comment]
@deboyblog 新版本是指微信的新版本还是jssdk的新版本？

**Comment by deboyblog** [comment]
@limichange jssdk

**Comment by luxueyan** [comment]
改title和jssdk有关系吗，是不是微信新版本会解决这个问题？

**Comment by deboyblog** [comment]
@luxueyan 是的 微信官方已经说了 在新版的jssdk会提供动态修改title的Api

**Comment by luxueyan** [comment]
@deboyblog  thx！

**Comment by always2tate** [comment]
这才是正解！！！！
![image](https://cloud.githubusercontent.com/assets/17022680/23986398/e7203634-0a5e-11e7-80e5-dc5d3d73f512.png)

**Comment by airyland** [comment]
@always2tate 希望微信官方开个发公告的地方或者把文档写详尽点，每次大家都发邮件过去问也是麻烦。

**Comment by isslayne** [comment]
保持关注

**Comment by xuqingkuang** [comment]
@always2tate 明显不是腾讯的官方地址，目前还没收到 WKWebview 正式上线的通知。

**Comment by deboyblog** [comment]
@xuqingkuang 是qq的邮箱 你可能看反了...

**Comment by deboyblog** [comment]
最新版iOS微信 已经可以修改了

**Comment by airyland** [comment]
亲测确实可用。

**Comment by maxyzli** [comment]
感谢回报
