### ISSUE TITLE
所有的资源文件都重新加载了一次（没有设置缓存的情况下）

### ISSUE THREAD

**Issue by xlei1123** [deboyblog/vue-wechat-title#20]
vue 单页面应用，在组件使用了v-wechat-title的时候 所有的资源文件都重新加载了一次（没有设置缓存的情况下），不知道是不是iframe引起的，望重视！！！

**Comment by xlei1123** [comment]
确实修改了标题 但是也带来了新问题

**Comment by deboyblog** [comment]
@xlei1123 设置下 `img-set` 属性 并且保证该路径的图片能访问 建议在 `static` 目录下放一个静态的小图
