### ISSUE TITLE
需要二次手动刷新才能生效

### ISSUE THREAD

**Issue by YuFengDing** [deboyblog/vue-wechat-title#23]

**Comment by deboyblog** [comment]
@YuFengDing 
提供机型
使用场景(哪个App/浏览器下打开的) 
贴上使用代码

**Comment by YuFengDing** [comment]
之前微信调试工具里试一直是这样，用真机发现该问题不存在  先关吧

**Comment by deboyblog** [comment]
微信开发者工具是存在这个问题的 但是微信客户端不存在 不用担心 有人提到这个问题了
