### ISSUE TITLE
title是后台获取的 利用这个插件怎么做比较好 没用到vuex

### ISSUE THREAD

**Issue by yrmatou** [deboyblog/vue-wechat-title#25]

**Comment by deboyblog** [comment]
定义一个 `computed` 变量 `cache` 设置为 `false`
通过 `localStorage` 来读取和更改
> App.vue
```
computed: {
    title: {
      cache: false,
      get () {
        return window.localStorage.getItem('title') || 'default title'
      }
   }
 }
```
> any component
```
window.localStorage.setItem('title', 'your real title')
```

**Comment by yrmatou** [comment]
谢谢

**Comment by yrmatou** [comment]
发现一个问题 需要二次刷新 手机上也有这个问题 放到哪个生命周期里面比较好

**Comment by deboyblog** [comment]
贴上你部分代码我看下

**Comment by yrmatou** [comment]
settitle(title){
    window.localStorage.setItem('title', title)
  },
activated() {
		console.log('active', this.infoMessage.title)
		this.$utils.settitle(this.infoMessage.title)
	},

**Comment by deboyblog** [comment]
infoMessage.title 能保证组件加载时就有值的么
试试更改完成加上这一句
```
settitle(title){
  window.localStorage.setItem('title', title)
  this.$nextTick() // Vue.nextTick()
}
```

**Comment by yrmatou** [comment]
好的，我回去试试。谢谢

**Comment by wangqiao2** [comment]
有值 感觉到这个页面就是setItem在 getItem 之后

**Comment by yrmatou** [comment]
有值 感觉到这个页面就是setItem在 getItem 之后 所以新页面的title就显示上一页面的title
