### ISSUE TITLE
readme文档疑惑

### ISSUE THREAD

**Issue by Jogiter** [deboyblog/vue-wechat-title#27]
> 作用
Vuejs 单页应用在iOS系统下部分APP的webview中 标题不能通过 document.title = xxx 的方式修改 该插件只为解决该问题而生(兼容安卓)

最终实现的还是依赖 `document.title = xxx ` ，不明白兼容处理是怎么实现的

**Comment by deboyblog** [comment]
@Jogiter
https://github.com/deboyblog/vue-wechat-title/blob/2.0/vue-wechat-title.js
源码很简单 通过加载一个空的隐藏的 `iframe` 设置标题实现的 `hack`
