### ISSUE TITLE
本地localStorage数据没了

### ISSUE THREAD

**Issue by wekerSnail** [deboyblog/vue-wechat-title#28]
苹果/ios/10.3

## 应用场景 应用版本信息
如: 
app中

## 代码

怎么引入的 
> main.js
```
Vue.use(require('vue-wechat-title'))
```
怎么使用的
> router.js
```
 path: '/roomOrderSub',
      name: 'RoomOrderSub',
      meta: {
        title: '订单提交'
      },
      component: RoomOrderSub
```
> App.vue
```
// show me you code
```
## 是否使用websocket或者其他跨域请求
有跨域

## 与预期不符的情况
原本存在于localStroage中的数据清空了
如果浏览器报错了 报什么错了?

**Comment by deboyblog** [comment]
@wekerSnail `img-set`属性设置了吗？图片地址是同域的还是跨域的

**Comment by wekerSnail** [comment]
没有设置，我只需要设置title，我是在ios app中使用的，ios端通过检测url变化来更改tiitle，但是貌似使用这种方式那边也是检测不到的

**Comment by deboyblog** [comment]
App? 使用HBuilder打包的吗？ 
没有尝试这样做 不过你如果用App打包的话 不需要使用这个插件 自定义导航栏不就可以实现了吗？
