### ISSUE TITLE
QQ浏览器进入页面会再次跳转前往/favicon.ico

### ISSUE THREAD

**Issue by stinyami** [deboyblog/vue-wechat-title#29]
## 机型/系统/版本

苹果/ios/10.3

## 应用场景 应用版本信息

QQ浏览器
版本号8.5.1.8451

## 代码

怎么引入的 

> main.js
```
import VueWechatTitle from 'vue-wechat-title'
Vue.use(require('vue-wechat-title'))
```

怎么使用的

> router.js
```
{
  path: '/invest_index', //首页-理财首页
  component: invIndex,
  meta: {
    title: '小鸽理财',
    needLogin: false,
  }
},
```

> App.vue
```
<template>
  <div id="app">
    <router-view v-wechat-title="$route.meta.title"></router-view>
  </div>
</template>
```

## 是否使用websocket或者其他跨域请求
没有

## 与预期不符的情况

进入页面会瞬间再次跳转到域名根目录的/favicon.ico路径下
如：
进入wap.xiaogelicai.com（这也是我使用的项目）
进入网站首页
然后瞬间再次跳转往wap.xiaogelicai.com/favicon.ico
vue-router没有这个路径 给出404页面
造成用户进入我们网站瞬间404现象

尝试过的操作：
根目录下添加favicon.ico图标（无效）
static目录下添加favicon.ico图标（无效）

根目录下index.html的head里这样编写：
```
<link rel="ico" type="image/x-icon" href="./favicon.ico">
<link rel="shortcut icon" type="image/x-icon" href="./favicon.ico">
```

**Comment by deboyblog** [comment]
@TinGYooooo 
抱歉这么久才回复 这段时间换工作没有注意到邮箱的issues提醒
目前还不知道什么原因 建议你检测到QQ浏览器的UA先禁用该插件
不过看来加载iframe会触发QQ浏览器的特定的页面刷新机制 我会尝试用加载空白图片的base64地址 或者针对QQ浏览器采用其他可行方案

**Comment by stinyami** [comment]
@deboyblog 
谢谢大佬，那我就先根据UA判断禁用掉吧~QQ浏览器也没什么用户群体……

**Comment by deboyblog** [comment]
@Tin-Yamileth 请尝试安装最新版本
