### ISSUE TITLE
favicon.ico 404 (Not Found)

### ISSUE THREAD

**Issue by yuzhou423** [deboyblog/vue-wechat-title#3]
用你的项目（http://vue-wechat-title.deboy.cn/#!/home）在微信编辑器上看到是这个结果：
vue-wechat-title.js:21   GET http://vue-wechat-title.deboy.cn/favicon.ico 404 (Not Found)，请问，这个bug可以解决吗？其他浏览器不显示！

**Comment by deboyblog** [comment]
这个你自己加一个站标就可以了

**Comment by deboyblog** [comment]
这个你自己加一个站标就可以了

**Comment by yuzhou423** [comment]
嗯嗯，没打包，npm run dev下，不管图片放哪，会一直显示这个问题，npm run build之后，把图片放到打包之后的根目录就没问题了，需要访问打包之后的代码！
