### ISSUE TITLE
在vue-router  hash模式时，会出现页面多次重载的情况

### ISSUE THREAD

**Issue by 215687950** [deboyblog/vue-wechat-title#30]
## 机型/系统/版本
小米/安卓/6.0

苹果/ios/10.3

## 应用场景 应用版本信息
如: 
在微信中打开 
应用版本号: 6.6.1

## 代码

怎么引入的 
> main.js
```
// show me you code
```
怎么使用的
> router.js
```
// show me you code
```
> App.vue
```
// show me you code
```
## 是否使用websocket或者其他跨域请求
有/没有

## 与预期不符的情况

如果浏览器报错了 报什么错了?

**Comment by jokerxm0611** [comment]
问题+1   
测试环境
谷歌浏览器(68.0.3440.106) 微信开发者工具(1.02.1808101)
"vue-wechat-title": "^2.0.4"

router/index
export default new Router({
  routes: [
    {
    	path: '/',
    	name: 'home',
    	component: home,
    	meta: {
    		title: '首页',
        index: 0,
        showFooter: true
    	}
    },
    {
    	path: '/list',
    	name: 'list',
    	component: list,
    	meta: {
    		title: '列表页',
        index: 1,
        showFooter: true
    	}
    },
]
})
Vue.use(require('vue-wechat-title'));

app.vue

 <@@router-view v-wechat-title="$route.meta.title" class="child-view"></router-view>

他会先载入当前vue    然后重载两次hone.vue  一共载入3次

**Comment by deboyblog** [comment]
@jokerxm0611 @215687950 请尝试传递
```
data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7
```
到`img-set`属性中去

**Comment by deboyblog** [comment]
@215687950 @jokerxm0611 经最新版的测试后 在我的机子上没有出现你们描述的BUG 请提供详细重现环境 或者尝试安装最新版 2.0.5
