### ISSUE TITLE
在开发过程中，引入后会导致刷新或切换页面时 main.js 加载多次。影响路由监听

### ISSUE THREAD

**Issue by SnowBeatRain** [deboyblog/vue-wechat-title#31]
## 机型/系统/版本
小米/安卓/6.0

苹果/ios/10.3

## 应用场景 应用版本信息
如: 
在微信中打开 
应用版本号: 6.6.1

## 代码

怎么引入的 
> main.js
```
// show me you code
```
怎么使用的
> router.js
```
// show me you code
```
> App.vue
```
// show me you code
```
## 是否使用websocket或者其他跨域请求
有/没有

## 与预期不符的情况

如果浏览器报错了 报什么错了?

**Comment by deboyblog** [comment]
@SnowBeatRain 请问安装最新版还会出现你描述的情况吗？

**Comment by deboyblog** [comment]
长时间无响应 且提问未按照规范 关闭了
