### ISSUE TITLE
Resource interpreted as Document but transferred with MIME type image/gif

### ISSUE THREAD

**Issue by hackwaly** [deboyblog/vue-wechat-title#32]
chrome浏览器报warning：
vue-wechat-title.js:21 Resource interpreted as Document but transferred with MIME type image/gif: "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7".

有办法避免吗？

**Comment by deboyblog** [comment]
@hackwaly 这个不需要管 实在不爽你可以在开发阶段不启用插件
