### ISSUE TITLE
手机QQ设置不生效

### ISSUE THREAD

**Issue by jasperqin9068** [deboyblog/vue-wechat-title#34]

**Comment by deboyblog** [comment]
帖完整的设置代码进来

**Comment by zackqin9068** [comment]
// main.js
Vue.use(require('vue-wechat-title'))

// App.vue
<router-view v-wechat-title="$route.meta.title"/>

// routes.js
{
path: '/query',
name: 'query',
meta: {
title: '查询'
},
component: () => import('../../pages/query/Query') //此处跟文档的不一致，是否是这个原因造成的？
},
就是这么设置的，在手机QQ IOS版本不能正常显示，但是在支付宝跟微信都能正常显示

**Comment by CaniceZ** [comment]
用的是你的demo，qq扫码会生效，复制链接到qq打开不生效
