### ISSUE TITLE
iosqq不通过二维码扫码直接复制链接会无效

### ISSUE THREAD

**Issue by CaniceZ** [deboyblog/vue-wechat-title#36]
http://vue-wechat-title.deboy.cn/?from=singlemessage&isappinstalled=0
复制链接在qq打开
效果图：
![Uploading image.png…]()

**Comment by CaniceZ** [comment]
![image](https://user-images.githubusercontent.com/23026625/60972100-297cb900-a358-11e9-8889-cd52c4da7e2d.png)

**Comment by deboyblog** [comment]
这个程序内部处理，默认地址上带上/?#/就可以了
