### ISSUE TITLE
waring

### ISSUE THREAD

**Issue by BH-GeGe** [deboyblog/vue-wechat-title#38]
## 机型/系统/版本
小米/安卓/6.0

苹果/ios/10.3

## 应用场景 应用版本信息
如: 
在微信中打开 
应用版本号: 6.6.1

## 代码

怎么引入的 
> main.js
```
// show me you code
```
怎么使用的
> router.js
```
// show me you code
```
> App.vue
```
// show me you code
```
## 是否使用websocket或者其他跨域请求
有/没有

## 与预期不符的情况
Resource interpreted as Document but transferred with MIME type image/gif: "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7".
如果浏览器报错了 报什么错了?

**Comment by deboyblog** [comment]
这个不影响网页 如果觉得不舒服 可以设置 img-set 数据 指向一个任意图片
