### ISSUE TITLE
异步调用，新页面的title就显示上一页面的title

### ISSUE THREAD

**Issue by gh0sthx** [deboyblog/vue-wechat-title#39]
## 机型/系统/版本
和机型无关
## 应用场景 应用版本信息
在微信中打开 
应用版本号: 6.6.1

## 代码
```
that.$nextTick(() => {
                        // that.$route.meta.title = that.goods.Name;
 })
```
> App.vue
```
<div id="app" v-cloak>
    <router-view v-wechat-title="$route.meta.title"></router-view>
  </div>
```
## 是否使用websocket或者其他跨域请求
有，跨域了

## 与预期不符的情况
异步调用，新页面的title就显示上一页面的title。我的需求是在当前页面变更参数来push新页面的，不过我觉得和这个没有关系。

## 解决方案
```
export function setTitle(title) {
  setTimeout(() => {
    document.title = title;
    var iframe = document.createElement('iframe');
    iframe.style.visibility = 'hidden'
    iframe.style.width = '1px'
    iframe.style.height = '1px'
    iframe.onload = function() {
      setTimeout(function() {
        document.body.removeChild(iframe)
      },0)
    }
    document.body.appendChild(iframe)
  })
```

**Comment by gh0sthx** [comment]
this.$http
                    .get("/goods", { params: { id: that.id } })
                    .then(res => {
                        this.$vux.loading.hide();
                        if (res.status == 200) {
                            that.goods = res.data;
                            that.$nextTick(() => {
                                that.$route.meta.title = that.goods.name;
                            })
                    })
                    .catch(function(error) {});

**Comment by deboyblog** [comment]
@Paladinhanxiao 把title变量放到store里面去 不要通过修改route的信息来变更
