### ISSUE TITLE
图片地址自定义

### ISSUE THREAD

**Issue by cismous** [deboyblog/vue-wechat-title#5]
iframe.setAttribute('src', '/favicon.ico')

需求： 第二个参数能否提供自定义功能呢
分析： 由于目前固定的链接是favicon.ico, 控制台会提醒 `Resource interpreted as Document but transferred with MIME type image/x-icon: "http://localhost:3001/favicon.ico`

**Comment by deboyblog** [comment]
这个在build之后 把站标文件放在服务器静态页面根目录即可
不过这个自定义图片地址的功能等我这段时间忙完就加上
