### ISSUE TITLE
使用后引发的v-model bug

### ISSUE THREAD

**Issue by cismous** [deboyblog/vue-wechat-title#6]
`<textarea v-model="message" placeholder="评价更多内容可获得更多积分奖励"/>`
上面这个代码，在使用的时候，发现输入的内容会重复一遍，比如输入`你好`，就会变成`你好你好`，
bug出现在微信端

**Comment by deboyblog** [comment]
@cismous 方便贴代码复现吗？ 我这用了这么久，也没出现这种如此诡异的情况... 而且这从代码层面上 我这个插件是不可能引起这种BUG的吧..![qq20170316-171438](https://cloud.githubusercontent.com/assets/11410323/23989115/2b055d22-0a6c-11e7-9331-5400bfa1b991.png)

**Comment by cismous** [comment]
https://gist.github.com/cismous/7eb1008e8af1118c2fc9b47bb53c1aa9

pc开发调试问题是没有出现的，就在微信上调试发现的

**Comment by deboyblog** [comment]
在其他浏览器和PC端甚至其他机型 有检查过吗

**Comment by cismous** [comment]
原因找到了，是因为vue中的一个变量变化，导致setWechatTitle重新执行了一次，可能触发了什么，所以我的解决方案是

`            if (title === undefined) {
                return
            }
`
后面加上
`
            if (document.title === title) {
                return
            }
`
相同的标题，就不执行setWechatTitle了

你有更好的办法吗？
如果觉得我的方法可行，我可以提交一个pull request，或者需要我进一步测试吗？

**Comment by deboyblog** [comment]
已用你的方案解决
