### ISSUE TITLE
最新版提示‘getAttribute’未定义

### ISSUE THREAD

**Issue by shengwong233** [deboyblog/vue-wechat-title#7]
最新版提示‘getAttribute’未定义

**Comment by deboyblog** [comment]
请提供Vuejs版本、vue-wechat-title的版本

**Comment by deboyblog** [comment]
@a416237796 请移除重新安装 是我昨晚更新了1.x版本导致的最新版变成vuejs1.x适用版本了 现在才是默认安装2.0.4版本

**Comment by shengwong233** [comment]
解决了，3q
