### ISSUE TITLE
请问“img-set="/static/logo.png"“设这个是干什么用呢？

### ISSUE THREAD

**Issue by zzmm1** [deboyblog/vue-wechat-title#9]
谢谢，项目已经在2.0的vue上正常跑起来了，但我不明白这个是img-set是做什么的，可以不要吗？

**Comment by zzmm1** [comment]
感谢你，请问我用this.$route.meta.title =title这种方式修改title，但也不好使，有时候有用，有时候没用，请问这是怎么回事呢。

**Comment by deboyblog** [comment]
可以不用 插件原理是通过加载iframe来实现修改标题 而这个img-set是设置iframe的src的 最好设置成站标 或者选择比较小的图片地址 比如：logo 可以避免浏览器报404错误
